### ISSUE TITLE
Gen 1 Virtual Console -- Feature Request

### ISSUE THREAD

**Issue by pkmaster22341** [BernardoGiordano/PKSM#198]
If possible, it would be greatly appreciated if you could add compatibility with the Gen 1 Virtual console games since these pokemon will be able to be transferred to Gen 7 soon. Thanks!

**Comment by Orionsilver** [comment]
@pkmaster22341 
use JKSM to get the sav.dat on the JKSM for ur VC RBGY game and use PKHeX

**Comment by endrift** [comment]
If I may ask, what was the reasoning behind this being closed? I can probably actually do this myself if I get a way to interface with VC saves, as I already have written code for extracting gen I/II Pokémon from saves for another project. (I don't have code to modernize it yet but I've been hoping to write that soon.) Reinjecting is the real problem though.

If the PR wouldn't be merged though I won't bother porting it to PKSM.

**Comment by BernardoGiordano** [comment]
I closed this because at the time, I said in multiple places *I* didn't have time/will to port gen1 VC compatibility to PKSM. Obviously, if you can work around this, it will be surely merged if this will be completed sometimes. You could base yourself on @Naxann's [RgbySM](https://github.com/Naxann/RgbySM) and work with him into directly developing this into PKSM, if you want. RgbySM was meant to be a standalone application who could interface with PKSM's extra storage function.

**Comment by greenDarkness** [comment]
@endrift This may also be of use to you. It's a gen1 Pokemon Bank application.
https://github.com/gocario/PHBankGB
