### ISSUE TITLE
Feature Request: Load server over both HTTP and HTTPS

### ISSUE THREAD

**Issue by BetaLeaf** [BernardoGiordano/PKSM#306]
The current implementation of PKSM will load the server that allows you to inject pokemon via servepkx as http. Can it in addition be loaded as https? Websites that use zaksabeast/PKSMBrowserInject cannot send pokemon if the page is loaded via https as Chrome will block the request. My personal website uses an iframe to load the master zaksabeast/PKSMBrowserInject and since my website uses https by default, I have to use javascript and downgrade the page to http when the page is loaded.

**Comment by BetaLeaf** [comment]
You should be able to use a self-signed certificate. If not, a certificate can be generated from https://certbot.eff.org/

**Comment by zaksabeast** [comment]
Hey there!

I think this is better suited as a feature request within my repository that holds the browser inject client.

I'm also not quite sure I understand what you are trying to accomplish.  You're wanting to load the site in https only to downgrade it to http.  This makes sense if you want to privately host the browser inject, and you seem to know how to do it, but since it's already hosted on github for online usage and can be used locally for offline usage, the reasoning behind a different host escapes me.

If you are interested in this, you could definitely explain your reasoning as well as send a pull request to my repository, and I'd be happy to take a look.

Thanks! :)

**Comment by BetaLeaf** [comment]
Alright sorry if I wasn't clear. Right now PKSM only listens on HTTP. I want it to load on HTTP & HTTPS. When I host the browser inject client on my website, because my website by default runs on HTTPS, I have to use javascript to downgrade to HTTP. This is because while the browser inject client is running on HTTPS, chrome will block attempts to connect to HTTP. As such, when my website is running in HTTPS mode, chrome will block connection to the server. If it was also listening on HTTPS, then I could just simply connect to the server via HTTPS and not have to worry about downgrading clients to HTTPS. Does that clear any confusion up?

**Comment by BetaLeaf** [comment]
![image](https://cloud.githubusercontent.com/assets/7028351/23834185/84084fd4-0728-11e7-8e3a-47c9c99bab6d.png)

**Comment by BetaLeaf** [comment]
Incase you were wondering how I got it to downgrade to http:

`<script>
  if (location.protocol != 'http:')
{
 location.href = 'http:' + window.location.href.substring(window.location.protocol.length);
}
</script>
`
I'm still a newb to javascript so I just searched google for a solution. ;)

**Comment by BetaLeaf** [comment]
I didn't mean to close the issue. Sorry

**Comment by BernardoGiordano** [comment]
Honestly, I don't think it's a big problem, it would complicate more the code with too little benefits. Since you already found a workaround (and zak's webpage already loads up as html) I think I'll not work on this.

**Comment by BernardoGiordano** [comment]
If you can fix that webpage's code instead, that would be fine

**Comment by BetaLeaf** [comment]
Alright that's fair. I just don't like the idea of forcing downgrade from HTTPS to HTTP is all. Unfortunately, its not an issue with the website's code. Chrome is the issue here and they aren't going to do anything about it since it would only open up security holes in their browser. Thanks anyways.
