### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by jmx077** [BernardoGiordano/PKSM#333]
Hello just was wondering if it's possible to add  ribbons? And edit where Pokémon has come from say from Pokémon Y or mega ruby? If there is  please explain a little bit to me please on how to as I'm a little stupid lmao and thank you for your time.

**Comment by KofiMatson123** [comment]
Yes you are a little stupid😂😂 Just go to the pokemon editing screen and youll see a bunch of nubers shaped like a square at the top press it and youll be on a hex editor screen. Youll be able to edit locations and ribbons from here. To do that press all 4 corners of the bottom screen of the hex editor and the screen will turn from blue to pink, doing this allows you to do some major editing. Hope I helped😊

**Comment by Blitzle33** [comment]
"press all 4 corners of the bottom screen of the hex editor and the screen will turn from blue to pink, doing this allows you to do some major editing." Huh? What four corners? I'm confused.

**Comment by KofiMatson123** [comment]
The bottom screen in the hex editor. You press or touch all four sides of the bottom screen on the hex editor. Then the screen will turn pink. Try it before you ask again please

**Comment by jmx077** [comment]
lmao thank you KofiMatson123 I am just a little less stupid now

**Comment by KofiMatson123** [comment]
Your welcome😂😂😂 Took me like a whole week to figure it out😂😂😂😂

**Comment by jmx077** [comment]
I clicked on it but was like ah I don't want to mess in there I kinda knew but I dont know the coding tho. where do I learn to do that?

**Comment by KofiMatson123** [comment]
I dont know how to do coding lol😂 i just figured it out myself. I genned in bulbasaurs with different game tags so that I would know which game they come from. Also locations from games can be found from bulbapedia. But only location from BW to SM will be there. For example Pokemon from Hoenn (gen 3) will have 31 75 as a location from coming from hoenn, but to make them legit you have to get the right game tags for hoenn(gen 3) Ruby, Sapphire and Emerald. Find the others for Kanto, Sinnoh and Johto and the gamecube game. For the VC game ( Red, Blue and Yellow 3ds release) it would be 3D 75, for the game tag it would be 26. Hope some of this helps😉😊
