### ISSUE TITLE
Green screen 11.4

### ISSUE THREAD

**Issue by J00ker92** [BernardoGiordano/PKSM#354]
Green screen on 11.4 using doodlebomb and ninjahax what we cam do ? Thank you!

**Comment by KofiMatson123** [comment]
Theyve been patched and no longer work

**Comment by J00ker92** [comment]
So is not coming out a patch for pksm ?

**Comment by KofiMatson123** [comment]
Have you downloaded everything for PKSM?

**Comment by J00ker92** [comment]
Yes pksm folder to put inside the 3ds folder and the additional assets i run doodlebomb then hombrew and when i select pksm get stuk with green screen same sruff with chmm2

**Comment by KofiMatson123** [comment]
Have you updatef youre system to 11.4? If you have this may be the problem, PKSM and chmm2 have been patched for 11.4 but if youre on 11.3 or lower I dont know what the problem is. If you have updated your 3DS to 11.4 and  want to use them then youll need to buy another 3DS as there is no other way. Sorry

**Comment by J00ker92** [comment]
Dont thin so if they udpate pksm is work perfectly  homebrew is working on 11.4

**Comment by KofiMatson123** [comment]
Well just wait for an update then. Just use pkhex or something to edit what you need

**Comment by BernardoGiordano** [comment]
It should be a HBL problem. Wait for the payload to be updated

**Comment by J00ker92** [comment]
The playload is already on 11.4

**Comment by HoodieZz** [comment]
PKSM needs a new updated version for 11.4, the HBL is already updated

**Comment by zaksabeast** [comment]
The updated homebrew payload means you can run homebrew on your 3ds, but it doesn't mean it has access to your Pokemon saves.

Homebrew on 11.3 had this same things happen, and later had an update to support save access.

[A comment by lycan2500 on issue #352 ](https://github.com/BernardoGiordano/PKSM/issues/352#issuecomment-293732440) mentioned JKSM wasn't working either for this same reason.

In the end, it is not PKSM that needs updating to support 11.4.

**Comment by Naxann** [comment]
Yep, the payloads are not working right for save access. Save access is a special module to implement in Homebrew, and like @zaksabeast said, payload for 11.3 had an update for save access after it was out. 
Wait until a new payload for 11.4 is released. We will update this issue when it is available. Right now, you just have to wait, there is no other solution (even PkHex, since it needs to have access to a save manager on your 3DS).

**Comment by Tavku56** [comment]
Did they ever fix the payload?

**Comment by PixelNyan** [comment]
@Naxann Where can I get up to date info on the payloads. Like when the shit is fixed....

**Comment by BernardoGiordano** [comment]
new payloads have just been released and they fix the issue.
