### ISSUE TITLE
How to download poketransporter application

### ISSUE THREAD

**Issue by eskimodog** [BernardoGiordano/PKSM#699]
At the moment I have 3DS that uses 11.3 software. I currently am running homebrew and want to use this application on my gen 4 & 5 games. Is it possible to download the poketransporter application without having to update to download from the eshop?

**Comment by ihaveamac** [comment]
your best option is [custom firmware](https://3ds.hacks.guide) (which would allow you to update and not lose homebrew). since you are on 11.3 you can use the free soundhax method. your other option is ctr-httpwn, which lasts until the system is rebooted. either way, you could go on the eshop to download it without losing access to homebrew.

**Comment by eskimodog** [comment]
Tried using the custom firmware procedure and it updated my 3ds. Might use NTRboot.

**Comment by ihaveamac** [comment]
did you follow the guide to the end, or just skip to the end? because you're not supposed to update until after you are using luma.

**Comment by eskimodog** [comment]
Yes, I read through it slowly but I was misled to update the software prior to using luma.

**Comment by ihaveamac** [comment]
the guide doesn't do that, it only has that after you have luma running. the only way that's possible is if you didn't follow it correctly. what happens when you hold select when turning on?

**Comment by GriffinG1** [comment]
@ihaveamac do you mind moving that over to NH? This _really_ isn't the place for it..
