### ISSUE TITLE
Autocomplete the Pokédex when importing Pokémon to a gamesave.

### ISSUE THREAD

**Issue by jmarquezt** [BernardoGiordano/PKSM#73]
**# Expected Behavior**

When dragging a pokémon from the bank to the box of the game, the pokémon should be marked as seen and captured in the pokédex

**# Current Behavior**

The Pokémon is not being marked as seen or captured

**Comment by CAMPIZ20** [comment]
That´s because you simply put the Pokemon in the game, for the Pokedex marks it as captured  **you must trade it and then trade it back**

The same goes for the shinies, if you make a Pokemon shiny with PKSM you must trade it and then trade it back, because **(according to me)** the app only changes the data of the Pokemon not the complete game

**Comment by jmarquezt** [comment]
Well, If you look at PhBank or PhBankGB, when you put the Pokemon in the game from the bank it automatically marks it as captured in the Pokedex

**Comment by BernardoGiordano** [comment]
fixed in the 4.0.0alpha build
