### ISSUE TITLE
[ FIXED ] Some shinny's dont work

### ISSUE THREAD

**Issue by xNeoDarkness** [BernardoGiordano/PKSM#79]
PD: I was wrong, its only some sprites that doesnt change.
PD2: Pls if you can put an option to change gender !! Thanks for your work.

**Comment by Samuel8488** [comment]
You can change the level.

**Comment by xNeoDarkness** [comment]
Tell me how pls. I cant

**Comment by Samuel8488** [comment]
You update the PKSM?

**Comment by xNeoDarkness** [comment]
I did from the inapp option

**Comment by BernardoGiordano** [comment]
You have to install the app manually from the sd card, then.

Also, I think you didn't inform yourself well.
First of all, shinyzing stuff WORKS. It'0s only the in-app sprite that doesn't change, only for gen7 mons, because [this spritesheet](https://github.com/BernardoGiordano/PKSM/blob/master/assets/romfs/res/shinySpritesSmall.png) hasn't been completed yet.

Also, there's NO WAY that gengar doesn't apper to be shiny.

**Comment by xNeoDarkness** [comment]
Yes, its true. Is the sprite that doesnt change. Srry! I'll try to install the latest version manually

**Comment by xNeoDarkness** [comment]
All work correctly now! I have tones more options O_o wow...I can even change items and moves... 10/10

**Comment by lomejor18** [comment]
@BernardoGiordano this guy has almost all shiny, maybe it can help tu improve your app

https://github.com/msikma/pokesprite/tree/sumo-update

**Comment by NinjaBoyLao** [comment]
Trying to make glaceon shiny in alpha sapphire crashes the app, it just freezes and i cant do anything. installed pksm through homebr3w

**Comment by BernardoGiordano** [comment]
fixed
